version: '3.8'

services:
  app:
    container_name: secure-calendar-app
    build: .
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - swag_network
    # ports:
    #   - "8080:80"
    environment:
      - NODE_ENV=production

networks:
  swag_network:
    external: true
    name: swag_default
